FROM golang:alpine3.19 AS build
RUN mkdir /src
ADD ./*.go /src
ADD ./go.mod /src
ADD ./go.sum /src
WORKDIR /src
RUN go get -d -v -t
RUN GOOS=linux go build -v -o simple-go-demo
RUN chmod +x simple-go-demo

FROM alpine:3.19.1
COPY --from=build /src/simple-go-demo /usr/local/bin/simple-go-demo
EXPOSE 8080
CMD ["simple-go-demo"]
